name: Personal Training Feature
on:
  workflow_call:

jobs:
  component-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          clean-install: 'true'

      - name: Run components tests
        run: npm test

      - name: Generate test report
        run: echo 'No test report needed for Demo'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
  
  development:
    needs: component-testing
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build for development
        run: |
          echo 'Building for development environment'
          npm run build
 

  staging:
    needs: development
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to staging
        run: |
          echo 'Deploying membership features to staging'
          echo 'Environment URL: ${{ vars.APP_URL }}'
    

  production:
    needs: staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo 'Deploying membership features to production'
          echo 'Environment URL: ${{ vars.APP_URL }}'