name: Class Schedule CI/CD
on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: aaronmaj/github-actions/.github/actions/deployment/setup-node.yml@main
        with:
          node-version: '20.x'
          cache: 'npm'
          clean-install: 'false'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run lint
        run: NODE_OPTIONS='--experimental-vm-modules' npm run lint

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          push: false
          load: true
          tags: carved-rock/class_schedule:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.7.8
        with:
          start: npm run dev
          wait-on: 'http://localhost:3000'
          config-file: cypress.config.ts

  deploy-staging:
    needs: build-and-test
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Build for staging
        run: |
          echo 'Building class schedule feature to staging environment' 
          echo 'Run smoke tests against staging environment' 

      
  deploy-production: 
    needs: deploy-staging
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      
        - uses: actions/checkout@v4

        - name: Build for production
          run : |
            echo 'Building class schedule feature to production environment'
            docker build -t carved-rock/class_schedule:latest .

        - name: Deploy to production
          run: |
            echo 'Deploying class schedule feature to production environment'
            docker push carved-rock/class_schedule:latest
            echo 'Deployed class schedule feature to production environment'
