name: Membership Management Pipeline
on:
  workflow_call:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          severity: 'CRITICAL, HIGH'

  build:
    needs: security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/deployment/setup-node
        with:
          node-version: '20.x'
          cache: 'npm'
          clean-install: 'true'

      - name: Run lint
        run: npx eslint 'src/features/membership/**'

      - name: Build
        run: npm build

      - name: Test
        run: npm test -- --coverage --watchAll=false

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo 'Deploying membership features to production'
          echo 'Environment URL: ${{ vars.APP_URL }}'
